name: Security

on:
  push:
    branches: ["**"]
  pull_request:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  scan:
    permissions:
      contents: read
      pull-requests: read
    uses: garymike/security-workflows/.github/workflows/security-scan.yml@fbd11e574f4bfab4a132228457d33267609c8470 # main @ 2026-07-06
    secrets: inherit

  audit:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
    uses: garymike/security-workflows/.github/workflows/security-audit.yml@fbd11e574f4bfab4a132228457d33267609c8470 # main @ 2026-07-06
    secrets: inherit
